spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDISHOST:redis.iitbase.com}
      port: ${REDISPORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false # Redis has no ssl, that's for upstash
      timeout: 5000

jwt:
  secret: ${JWT_SECRET} # Must be a long, secure string
  expiration: ${JWT_EXPIRATION:86400000}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
  from-email: hello@iitbase.com

logging:
  level:
    com.iitbase: INFO
    org.springframework.security: WARN