spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDISHOST:localhost}
      port: ${REDISPORT:6379}
      timeout: 60000

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}

logging:
  level:
    com:
      iitbase: INFO
    org:
      springframework:
        security: DEBUG