package com.iitbase.recruiter.enums;

public enum TechRole {
    BACKEND_ENGINEER,
    FRONTEND_ENGINEER,
    FULL_STACK_ENGINEER,
    MOBILE_ENGINEER,
    DEVOPS_ENGINEER,
    PLATFORM_ENGINEER,
    SITE_RELIABILITY_ENGINEER,
    SECURITY_ENGINEER,
    QA_ENGINEER,
    EMBEDDED_ENGINEER,
    SOLUTIONS_ARCHITECT,
    ENGINEERING_MANAGER,
    OTHER
}
