package com.iitbase.job;

public enum PrimaryRole {
    SOFTWARE_ENGINEER,
    DATA_SCIENTIST,
    PRODUCT_MANAGER,
    DESIGNER,
    DEVOPS_ENGINEER,
    MACHINE_LEARNING_ENGINEER,
    FRONTEND_ENGINEER,
    BACKEND_ENGINEER,
    FULL_STACK_ENGINEER,
    MOBILE_ENGINEER,
    QA_ENGINEER,
    SECURITY_ENGINEER,
    ANALYST,
    RESEARCHER,
    OTHER
}